# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  required_plugins = %w( vagrant-vbguest vagrant-disksize )
    _retry = false
    required_plugins.each do |plugin|
        unless Vagrant.has_plugin? plugin
            system "vagrant plugin install #{plugin}"
            _retry=true
        end
    end

    if (_retry)
        exec "vagrant " + ARGV.join(' ')
    end

    config.vm.define "kanbanboard" do |kanbanboard|
        kanbanboard.vm.box = "ubuntu/bionic64"
        kanbanboard.vm.hostname = "kanbanboard"

        # App port
        kanbanboard.vm.network "forwarded_port", guest: 5000, host: 5000

        kanbanboard.vm.provider "virtualbox" do |vb|
            vb.name = "kanbanboard"
            vb.memory = "3072"
            vb.cpus = 2
        end
        bravetoolsvm.vm.synced_folder "../.", "/home/vagrant/workspace/src/github.com/adrozdov/kanbanboard"
        
        bravetoolsvm.vm.provision :shell, :privileged => false, :path => "bootstrap.sh"
    end
end